CREATE TABLE telemetry_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    node_device_id TEXT NOT NULL REFERENCES nodes (device_id),
    metric_name TEXT NOT NULL,
    payload_schema_name TEXT NOT NULL,
    payload_schema_version INT NOT NULL DEFAULT 1,
    payload JSONB NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_telemetry_records_payload_schema FOREIGN KEY (payload_schema_name, payload_schema_version) REFERENCES payload_schemas (name, version),
    PRIMARY KEY (id, recorded_at)
);

SELECT create_hypertable (
        'telemetry_records', 'recorded_at', chunk_time_interval => INTERVAL '7 days', if_not_exists => TRUE
    );

CREATE INDEX idx_telemetry_records_node_device_id ON telemetry_records (node_device_id);

CREATE INDEX idx_telemetry_records_metric_name ON telemetry_records (metric_name);

CREATE INDEX idx_telemetry_records_payload_schema_name_version ON telemetry_records (payload_schema_name, payload_schema_version);

CREATE INDEX idx_telemetry_records_recorded_at_desc ON telemetry_records (recorded_at DESC);

CREATE INDEX idx_telemetry_records_node_metric_recorded_at_desc ON telemetry_records (
    node_device_id,
    metric_name,
    recorded_at DESC
);

CREATE INDEX idx_telemetry_records_metric_recorded_at_desc ON telemetry_records (metric_name, recorded_at DESC);

CREATE INDEX idx_telemetry_records_payload_gin ON telemetry_records USING GIN (payload);
