CREATE TYPE node_log_level AS ENUM ('NONE', 'ERROR', 'WARN', 'INFO', 'DEBUG');

CREATE TABLE node_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    node_device_id TEXT NOT NULL REFERENCES nodes (device_id),
    level node_log_level NOT NULL DEFAULT 'NONE',
    tag TEXT NOT NULL DEFAULT '',
    message TEXT NOT NULL,
    logged_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, logged_at)
);

SELECT create_hypertable (
        'node_logs', 'logged_at', chunk_time_interval => INTERVAL '7 days', if_not_exists => TRUE
    );

CREATE INDEX idx_node_logs_node_device_id ON node_logs (node_device_id);

CREATE INDEX idx_node_logs_level ON node_logs (level);

CREATE INDEX idx_node_logs_logged_at_desc ON node_logs (logged_at DESC);

CREATE INDEX idx_node_logs_node_logged_at_desc ON node_logs (node_device_id, logged_at DESC);

CREATE INDEX idx_node_logs_level_logged_at_desc ON node_logs (level, logged_at DESC);

ALTER TABLE node_logs SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'node_device_id',
    timescaledb.compress_orderby = 'logged_at DESC'
);

SELECT add_compression_policy ('node_logs', INTERVAL '1 week');
