CREATE TYPE action_status AS ENUM (
    'UNEXECUTED',
    'UNRESPONDED',
    'FAILED',
    'SUCCESS'
);

CREATE TABLE action_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    execution_id UUID NOT NULL,
    action_id UUID NOT NULL REFERENCES actions (id),
    node_id UUID REFERENCES nodes (id),
    action_status action_status NOT NULL DEFAULT 'UNRESPONDED',
    action_message TEXT,
    payload JSONB NOT NULL,
    executed_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, executed_at)
);

SELECT create_hypertable (
        'action_logs', 'executed_at', chunk_time_interval => INTERVAL '7 days', if_not_exists => TRUE
    );

CREATE INDEX idx_action_logs_action_id ON action_logs (action_id);

CREATE INDEX idx_action_logs_execution_id ON action_logs (execution_id);

CREATE INDEX idx_action_logs_node_id ON action_logs (node_id);

CREATE INDEX idx_action_logs_action_status ON action_logs (action_status);

CREATE INDEX idx_action_logs_payload_gin ON action_logs USING GIN (payload);

CREATE INDEX idx_action_logs_executed_at_desc ON action_logs (executed_at DESC);

CREATE INDEX idx_action_logs_node_action_executed_at_desc ON action_logs (
    node_id,
    action_id,
    executed_at DESC
);

CREATE INDEX idx_action_logs_action_executed_at_desc ON action_logs (action_id, executed_at DESC);

CREATE INDEX idx_action_logs_status_executed_at_desc ON action_logs (action_status, executed_at DESC);
